# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d680cbfe619ee361fb6dcb204585c64d5c2e7f534fb32480bf2e58039a6a7eba382a32f4e9286a817eefe5d7bff129aabd4b4ba09bfe86ecbb9077f195c4ce

test:
  secret_key_base: dfa73c48048d6742abd1206e921046bb7e7f77db0c22bf38b1a55d87d20446c834860cf6c5245cc5ca4c1469ddb4f9f575264ad62b51669abf2a62c0db607eeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
